## Array

##### array
- matrix가 2차원 배열이라면, array는 다차원의 배열이다.
- 행렬을 2차원 이상으로 확장시킨 object이다.
- 배열은 일반적으로 3차원 이상의 차원을 갖는 object이다.

##### 생성
- array(data = NA, dim = length(Data), dimname = NULL)

In [2]:
aArray <- array(c(11:13,21:23,31:33), dim=c(3,2,3))
aArray    #3행, 2열, 3차원

, , 1

     [,1] [,2]
[1,]   11   21
[2,]   12   22
[3,]   13   23

, , 2

     [,1] [,2]
[1,]   31   11
[2,]   32   12
[3,]   33   13

, , 3

     [,1] [,2]
[1,]   21   31
[2,]   22   32
[3,]   23   33

UCBAdmissions으로 array실습

In [3]:
UCBAdmissions

, , Dept = A

          Gender
Admit      Male Female
  Admitted  512     89
  Rejected  313     19

, , Dept = B

          Gender
Admit      Male Female
  Admitted  353     17
  Rejected  207      8

, , Dept = C

          Gender
Admit      Male Female
  Admitted  120    202
  Rejected  205    391

, , Dept = D

          Gender
Admit      Male Female
  Admitted  138    131
  Rejected  279    244

, , Dept = E

          Gender
Admit      Male Female
  Admitted   53     94
  Rejected  138    299

, , Dept = F

          Gender
Admit      Male Female
  Admitted   22     24
  Rejected  351    317


In [4]:
UCBAdmissions[,,1]

          Gender
Admit      Male Female
  Admitted  512     89
  Rejected  313     19

In [5]:
# 각 학과의 남자 합격생
UCBAdmissions[1,1,]

A   B   C   D   E   F 
512 353 120 138  53  22

In [6]:
# 각 학과의 여자 합격생
UCBAdmissions[1,2,]

A   B   C   D   E   F 
 89  17 202 131  94  24

In [32]:
#삭제하기
ary1 <- array(1:8, dim = c(2,2,2))
ary1
ary1[,,-1]

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

[,1] [,2]
[1,] 5    7   
[2,] 6    8

#### 과제
- Array로 된 내장데이터를 찾아서 rowsums(...,dim=1) 해보고, 하드에 저장해보기

In [16]:
AirPassengers
dim(AirPassengers) #array가 아님

     Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
1949 112 118 132 129 121 135 148 148 136 119 104 118
1950 115 126 141 135 125 149 170 170 158 133 114 140
1951 145 150 178 163 172 178 199 199 184 162 146 166
1952 171 180 193 181 183 218 230 242 209 191 172 194
1953 196 196 236 235 229 243 264 272 237 211 180 201
1954 204 188 235 227 234 264 302 293 259 229 203 229
1955 242 233 267 269 270 315 364 347 312 274 237 278
1956 284 277 317 313 318 374 413 405 355 306 271 306
1957 315 301 356 348 355 422 465 467 404 347 305 336
1958 340 318 362 348 363 435 491 505 404 359 310 337
1959 360 342 406 396 420 472 548 559 463 407 362 405
1960 417 391 419 461 472 535 622 606 508 461 390 432

NULL

In [19]:
dim(Titanic)  
#4차원 - 4행(class), 2열(sex), 2(age = child, adult), 2(survived=No, Yes)

T <- Titanic

[1] 4 2 2 2

In [21]:
write.csv(T,"Titanic.csv") #csv로 저장

#### melt.array

- 차원축소
- 데이터 전처리 시, 유용하게 사용

In [29]:
a <- array(c(1:23, NA),c(2,3,4))
a

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   NA

In [28]:
library(reshape)
melt(a) 

#첫번째 줄은 행, 열번호, 테이블번호, 값(vlaue) -->1

X1 X2 X3 value
1  1  1  1   1   
2  2  1  1   2   
3  1  2  1   3   
4  2  2  1   4   
5  1  3  1   5   
6  2  3  1   6   
7  1  1  2   7   
8  2  1  2   8   
9  1  2  2   9   
10 2  2  2  10   
11 1  3  2  11   
12 2  3  2  12   
13 1  1  3  13   
14 2  1  3  14   
15 1  2  3  15   
16 2  2  3  16   
17 1  3  3  17   
18 2  3  3  18   
19 1  1  4  19   
20 2  1  4  20   
21 1  2  4  21   
22 2  2  4  22   
23 1  3  4  23   
24 2  3  4  NA

array에 이름 붙여주기

In [30]:
melt(a, varnames = c("X","Y","Z")) 

X Y Z value
1  1 1 1  1   
2  2 1 1  2   
3  1 2 1  3   
4  2 2 1  4   
5  1 3 1  5   
6  2 3 1  6   
7  1 1 2  7   
8  2 1 2  8   
9  1 2 2  9   
10 2 2 2 10   
11 1 3 2 11   
12 2 3 2 12   
13 1 1 3 13   
14 2 1 3 14   
15 1 2 3 15   
16 2 2 3 16   
17 1 3 3 17   
18 2 3 3 18   
19 1 1 4 19   
20 2 1 4 20   
21 1 2 4 21   
22 2 2 4 22   
23 1 3 4 23   
24 2 3 4 NA